FROM r-base:latest

# Should we install NCBI-BLAST?
ENV BLAST_INSTALL='Y'

# Main environmental variables
ENV DEPLOYMENT=/programs/deployment
ENV DEPS=$DEPLOYMENT/deps
ENV ARCH=$DEPS/arch
ENV DATA=$DEPLOYMENT/data
ENV IMPORTS=$DEPLOYMENT/imports
ENV PATH=$PATH:$DEPS/flash:$DEPS/cutadapt/bin:$DEPS/fastx/bin:$DEPS/igblast/bin
ENV PATH=$PATH:$DEPS/blast/bin
ENV TEMP=/tmp/deployment

# Add Root CA to make SSL function properly
# COPY ./deployment/zscaler.crt /usr/local/share/ca-certificates
# RUN update-ca-certificates

# Updates of the system and installation of additional prerequisites.
RUN apt-get update && apt-get install -y \
  file \
  python3-pip \
  python3-dev \
  virtualenv \
  curl \
  rsync \
  libcurl4-openssl-dev \
  libssl-dev \
  libgtextutils-dev \
# IgBLAST dependencies
  libxml2 \
  libxml2-dev \
  libuv1
  # libsqlite3-dev
  # git
  # cmake



RUN mkdir -p $TEMP/flash $TEMP/igblast
COPY . /programs

# Stash downloadable archives in a way compatible with docker caching
WORKDIR /archives
# RUN curl -SL https://ftp.ncbi.nih.gov/blast/executables/igblast/release/1.18.0/ncbi-igblast-1.18.0-x64-linux.tar.gz \
  # | tar -xzC $TEMP/igblast --strip-components 1
RUN tar -xzf ${DEPLOYMENT}/archives/ncbi-igblast-1.22.0_aarch64.tar.gz && mv ncbi-igblast-1.22.0_aarch64/* $TEMP/igblast

RUN curl -SL http://ccb.jhu.edu/software/FLASH/FLASH-1.2.11.tar.gz \
  | tar -xzC $TEMP/flash --strip-components 1
## wget https://ftp.ncbi.nih.gov/blast/executables/igblast/release/LATEST/ncbi-igblast-1.22.0-src.tar.gz
# Optional NCBI-Blast archive
RUN if [ $BLAST_INSTALL = 'Y' ]; then \
  mkdir -p $TEMP/blast; \
  curl -SL https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.15.0+-aarch64-linux.tar.gz \
  | tar -xzC $TEMP/blast --strip-components 1; fi
## wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.15.0+-aarch64-linux.tar.gz

# Set up the deployment environment
RUN mkdir -p $ARCH $DATA $IMPORTS \
             $DEPS/cutadapt $DEPS/fastx/src

RUN curl -k -SL https://github.com/agordon/fastx_toolkit/releases/download/0.0.14/fastx_toolkit-0.0.14.tar.bz2 \
   | tar -xjC $DEPS/fastx/src
## RUN tar xjf $ARCH/fastx_toolkit-0.0.14.tar.bz2 -C $DEPS/fastx/src

# move the stashed executables into final locations
RUN mv $TEMP/*blast $TEMP/flash $DEPS

# execute the remaining setup
WORKDIR $DEPLOYMENT
RUN bash ngs-ig_deploy.sh

# clean-up
RUN echo "### Removing the archives." && rm -rv $ARCH && \
    echo "### Checking the locations of new binaries ..." && \
    which flash cutadapt fastx_collapser igblastn blastn R && \
    # which flash cutadapt fastx_collapser R && \
    echo "### Done."
    

CMD bash test.sh
# ~/.docker/bin/docker build . -f ./Dockerfile-arm64 --platform=linux/arm64 --tag=vladimirvig/ngs-ig:20240709 --progress=plain